In [1]:
import torch 
torch.__version__ 

'1.0.1'

In [2]:
x = torch.empty(5, 3)
x

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.8049e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [3]:
# 随机值
x = torch.rand(5,3)
x 

tensor([[0.7993, 0.8945, 0.4422],
        [0.8694, 0.1116, 0.0062],
        [0.8745, 0.3672, 0.1324],
        [0.5240, 0.1751, 0.9508],
        [0.7875, 0.3841, 0.2546]])

In [4]:
 # 构建全0
 x = torch.zeros(5, 3, dtype=torch.long)
 x 

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [5]:
# 直接传入数据
x = torch.tensor([5.3, 3])
x

tensor([5.3000, 3.0000])

In [6]:
x = x.new_ones(5, 3, dtype=torch.double) # 继承了device 和 dtype的属性
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[ 0.2707,  0.2683, -0.9081],
        [-0.6269, -0.8675,  0.1518],
        [ 1.7256, -0.9472, -1.0004],
        [-0.1140, -0.4884,  0.2037],
        [ 2.8607, -1.7321,  0.0737]])

In [7]:
# 显示矩阵大小
x.size()

torch.Size([5, 3])

tensor([[0.2707, 0.2683, 0.9081],
        [0.6269, 0.8675, 0.1518],
        [1.7256, 0.9472, 1.0004],
        [0.1140, 0.4884, 0.2037],
        [2.8607, 1.7321, 0.0737]])

In [11]:
# 基本计算方法
y = torch.rand(5, 3)
y+x

tensor([[ 0.7175,  1.2551, -0.4345],
        [-0.5894, -0.5477,  0.9889],
        [ 1.9365, -0.9402, -0.7092],
        [ 0.1965, -0.3672,  0.6780],
        [ 3.6062, -1.2211,  0.9759]])

In [12]:
# 另一种假发
torch.add(x, y)


tensor([[ 0.7175,  1.2551, -0.4345],
        [-0.5894, -0.5477,  0.9889],
        [ 1.9365, -0.9402, -0.7092],
        [ 0.1965, -0.3672,  0.6780],
        [ 3.6062, -1.2211,  0.9759]])

In [13]:
y.add(x)

tensor([[ 0.7175,  1.2551, -0.4345],
        [-0.5894, -0.5477,  0.9889],
        [ 1.9365, -0.9402, -0.7092],
        [ 0.1965, -0.3672,  0.6780],
        [ 3.6062, -1.2211,  0.9759]])

In [14]:
# 索引
x[:, 1]

tensor([ 0.2683, -0.8675, -0.9472, -0.4884, -1.7321])

In [15]:
# torch.randn: 标准正态分布 torch.rand 均匀分布

In [16]:
#view操作可以改变矩阵维度
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [17]:
# 与numpy的协同操作
a = torch.ones(5)
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)