In [1]:
# 常见tensor形式
import torch
from torch import tensor

In [3]:
# Scalar 通常就是一个数值
x = tensor(42.)
x

tensor(42.)

In [4]:
x.dim()

0

In [6]:
2*x

tensor(84.)

In [7]:
x.item()

42.0

In [8]:
# Vecotr 向量 特征
v = tensor([1.5, -0.5, 3.0])
v

tensor([ 1.5000, -0.5000,  3.0000])

In [9]:
v.dim()

1

In [10]:
v.size()

torch.Size([3])

In [13]:
# Matrix 
M = tensor(
    [
        [1., 2.],
        [3., 4.]
    ]
)
M

tensor([[1., 2.],
        [3., 4.]])

In [14]:
M.matmul(M)

tensor([[ 7., 10.],
        [15., 22.]])

In [15]:
tensor([1., 0.]).matmul(M)

tensor([1., 2.])

In [16]:
M*M

tensor([[ 1.,  4.],
        [ 9., 16.]])

In [17]:
tensor([1., 2.]).matmul(M)

tensor([ 7., 10.])