In [1]:
import torch

In [2]:
# 方法1 手动定义 求导
x = torch.randn(3, 4, requires_grad=True)
x

tensor([[-0.5629, -0.5124,  1.0553,  2.7013],
        [-0.3510,  2.2774, -0.6707, -0.7416],
        [ 0.0337,  0.7530,  0.1476,  0.7292]], requires_grad=True)

In [3]:
# 方法2
x = torch.randn(3, 4)
x.requires_grad = True
x

tensor([[-1.1625, -0.4000,  0.2551, -0.2558],
        [ 0.3354, -0.9332,  0.6196, -0.4209],
        [-0.3089,  1.0688, -0.2588, -0.3890]], requires_grad=True)

In [4]:
b = torch.randn(3, 4, requires_grad=True)
t = x+b
y = t.sum()
y

tensor(7.2045, grad_fn=<SumBackward0>)

In [5]:
y.backward()

In [6]:
b.grad

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
# t没有指定requires_grad 但是会用到它 就会默认
print(
    x.requires_grad,
    b.requires_grad,
    t.requires_grad
)

True True True


In [8]:
# 计算流程
x = torch.randn(1)
b = torch.randn(1, requires_grad=True)
w = torch.randn(1, requires_grad=True)
y = w*x
z = y+b

In [9]:
print(
    x.requires_grad,
    b.requires_grad,
    w.requires_grad,
    y.requires_grad
)

False True True True


In [10]:
print(
    x.is_leaf,
    w.is_leaf,
    b.is_leaf,
    y.is_leaf,
    z.is_leaf
)

True True True False False


In [17]:
# 反向传播计算
z.backward(retain_graph=True) #如果不清空会累加起来

In [18]:
w.grad

tensor([4.6451])

In [19]:
b.grad

tensor([3.])